# SSH deploy key for ArgoCD to access the Git repo
# 1. Generate key: ssh-keygen -t ed25519 -C "argocd-first-sip" -f /tmp/argocd-deploy-key -N ""
# 2. Add public key as deploy key on GitHub (read-only): Settings > Deploy keys
# 3. Apply this secret with the private key filled in:
#    kubectl apply -f infra/argocd/repo-secret.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: first-sip-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:jimdaga/first-sip.git
  sshPrivateKey: |
    # REPLACE with contents of /tmp/argocd-deploy-key (private key)
    # DO NOT commit the actual key to the repo
---
# Helm chart repo (public, no auth needed)
apiVersion: v1
kind: Secret
metadata:
  name: first-sip-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: first-sip
  url: https://jimdaga.github.io/first-sip
